### ISSUE TITLE
login/password for (dev) site?

### ISSUE THREAD

**Issue by vfulco** [supermanzer/django_resume_builder#1]
I get error indicating no auth_table.  Newish to Django.  Thanks in advance.

**Comment by supermanzer** [comment]
Ah, right.  Sorry I totally neglected this.  I will be working on including a shell script that will create all the necessary tables and I'll update the repo as soon as that's ready. 

Here's the breakdown of the issue:
* The SQLite DB file is empty.
* Django comes with built in Authentication but it needs the DB tables to work.

Try the following commands executed in the terminal
```
docker exec -ti resume_app bash       # Getting access the Bash shell in the docker container
./manage.py makemigrations            # Creating the migration files for the initial models/tables
./manage.py migrate                   # Running the newly created migration files
./manage.py createsuperuser           # Creating an initial User object you will use to log in
```
Follow the terminal prompts for creating your superuser and then use those credentials to log in to the Resume Builder interface.

**Comment by supermanzer** [comment]
Hit the wrong button, sorry.  Let me know if that works for you.

**Comment by vfulco** [comment]
Will give a try over next week.  Thank you!

**Comment by supermanzer** [comment]
I have added a script that is run upon startup which creates the necessary tables and, if it detects no superuser was created, creates an initial superuser account.  Full details are provided in the updated README.  Please let me know if this resolves your issue.

**Comment by vfulco** [comment]
Everything seems to work on initial launch.  Now to get more familiar.  Thanks much.
